In [5]:
import numpy as np

In [9]:
# 3. Find the shape, size and dimension of the following array?
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(f"Array Shape: {arr.shape}")
print(f"Array Size: {arr.size}")
print(f"Array Dimension: {arr.ndim}")

Array Shape: (3, 4)
Array Size: 12
Array Dimension: 2


In [11]:
# 4. Write python code to access the first row of the following array?
arr = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

print(f"First row is: {arr[0]}")

First row is: [1, 2, 3, 4]


In [17]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

element = arr[2, 3]

print(f"Element at third row and fourth column: {element}")

Element at third row and fourth column: 12


In [18]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

array_flatten = arr.flatten()
odd_indexed_element = array_flatten[::2]
print(f"Odd Indexes Are: {odd_indexed_element}")

Odd Indexes Are: [ 1  3  5  7  9 11]


In [19]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

arr = np.random.rand(3,3)
print(arr)

[[0.54094939 0.80716061 0.39193575]
 [0.50812079 0.37139474 0.32365249]
 [0.46209211 0.31418204 0.12374039]]


In [21]:
# 9. Write code to increase the dimension of the following array?
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

increase_dimension = np.expand_dims(arr, axis = 0)
print(increase_dimension)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [22]:
# 10. How to transpose the following array in NumPy?
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

tenasposed_array = np.transpose(arr)
print(tenasposed_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [39]:
# 11. Consider the following matrix:
Matrix_A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

# Idex wise multiplication
array_multiply = Matrix_A2 * Matrix_B2
print(f"Index Wise Multiplication:\n {array_multiply}")

# Matix multiplication
Matrix_A2 = np.array([[1, 2, 3, 4], 
                      [5, 6, 7, 8], 
                      [9, 10, 11, 12]])

Matrix_B2 = np.array([[1, 2, 3], 
                      [4, 5, 6], 
                      [7, 8, 9], 
                      [10, 11, 12]])
matrix_multiply = Matrix_A2 @ Matrix_B2
print(f"Matix multiplication:\n {matrix_multiply}")

# Add both the matrix
Matrix_A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
addition_array = Matrix_A2 + Matrix_B2
print(f"Addition Array:\n {addition_array}")

# Subtact matrix B from A
substraction_array = Matrix_A2 - Matrix_B2
print(f"Substraction From B to A:\n {addition_array}")

# Devide Matrix B by A
division_array = Matrix_B2 / Matrix_A2
print(f"Division Array:\n{division_array}")

Index Wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matix multiplication:
 [[ 70  80  90]
 [158 184 210]
 [246 288 330]]
Addition Array:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Substraction From B to A:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Division Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
# 12. Which function in Numpy can be used to swap the byte order of an array?
arr = np.array([1, 256, 65536], dtype=np.int32)
swapped_arr = arr.byteswap()
print(swapped_arr)

[16777216    65536      256]


In [43]:
# 14. What does the np.reshape function do, and how is it used?
# Ans: The np.reshape function in NumPy is used to change the shape of an array without changing its data. This function allows you to transform an array into a different shape, provided that the total number of elements remains constant.
arr = np.arange(12)
reshapped_arr = arr.reshape(3,4)
print(reshapped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
# 15. What is broadcasting in Numpy?
# Ans: Broadcasting in NumPy is a set of rules and mechanisms that allow NumPy to perform element-wise operations on arrays of different shapes and sizes. It enables efficient computation by automatically expanding the smaller array to match the shape of the larger array without creating unnecessary copies of data.

# example
arr1 = np.array([[1,2,3], [11,22,33]])
arr2 = np.array([[23,24,25]])

Broadcasting_arr = arr1 + arr2
print(Broadcasting_arr)

[[24 26 28]
 [34 46 58]]
