In [8]:
import numpy as np

In [4]:
# 1. What is a Python library? Why do we use Python libraries?
# Ans: A Python library is a collection of pre-written code that developers can use to perform common tasks, making programming more efficient and less error-prone. Libraries provide reusable modules and functions for specific purposes, allowing you to avoid writing code from scratch for common functionalities. Here are some key points about Python libraries:
# Modularity: Libraries are organized into modules, which are files containing Python definitions and statements. These modules can be imported and used in your programs.
# Reusability: By using libraries, you can reuse existing, well-tested code instead of reinventing the wheel. This saves time and effort.
# Efficiency: Libraries often contain optimized and efficient implementations of algorithms and functions, which can improve the performance of your programs
# Specialization: There are libraries for a wide range of tasks, such as data analysis (e.g., Pandas, NumPy), web development (e.g., Django, Flask), machine learning (e.g., TensorFlow, scikit-learn), and more.

# ---Why Do We Use Python Libraries?--
# Ans:
# Simplicity: Libraries simplify the development process by providing ready-made solutions for common tasks.
# Reliability: Libraries are usually well-tested and debugged, reducing the likelihood of errors in your code.
# Productivity: By leveraging libraries, developers can focus on solving higher-level problems instead of dealing with low-level details.

# ---example---
import requests

response = requests.get('https://api.github.com')
if response.status_code == 200:
    print('Suppose Fetch Github API Email URL:', response.json()['emails_url'])
else:
    print('An error occurred.')


Suppose Fetch Github API Email URL: https://api.github.com/user/emails


In [15]:
# 2. What is the difference between Numpy array and List?
# Ans: NumPy arrays and Python lists are both used to store collections of data, but they have significant differences in terms of functionality, performance, and use cases. Here are the key differences:

# ---Numpy---
# NumPy Array: Elements in a NumPy array are of the same data type, which allows for efficient storage and operations.
# NumPy Array: NumPy arrays are more memory efficient and faster for numerical computations because they use contiguous memory blocks and are implemented in C.
# NumPy Array: Provides a wide range of mathematical, logical, and statistical operations. It supports multi-dimensional arrays, which are essential for scientific computing.
# NumPy Array: Supports advanced slicing and indexing, including boolean indexing and multi-dimensional slicing.

# Numpy example -------
# Creating a NumPy array
arr = np.array([1, 2, 3, 4])
# Element-wise operations
arr2 = arr * 2
print("Numpy Multiply Array with 2:",arr2)

#-------python list------
# Python List: Elements in a Python list can be of different data types (e.g., integers, floats, strings, objects).
# Python List: Lists are less efficient for numerical operations as they are implemented as dynamic arrays with additional overhead.
# Python List: Provides basic functionalities for data storage and manipulation but lacks advanced mathematical operations and multi-dimensional capabilities.
# Python List: Uses more memory because it stores elements as separate objects with pointers to each element, resulting in additional overhead.
# Python List: Supports basic slicing and indexing, but lacks the advanced features provided by NumPy arrays.

#python list example ------
# Creating a Python list
lst = [1, 2, 3, 4]
# Element-wise operations (must be done manually)
lst2 = [x * 2 for x in lst]
print("in list After Manualy multiply with 2:",lst2)

Numpy Multiply Array with 2: [2 4 6 8]
in list After Manualy multiply with 2: [2, 4, 6, 8]


In [16]:
# 3. Find the shape, size and dimension of the following array?
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(f"Array Shape: {arr.shape}")
print(f"Array Size: {arr.size}")
print(f"Array Dimension: {arr.ndim}")

Array Shape: (3, 4)
Array Size: 12
Array Dimension: 2


In [17]:
# 4. Write python code to access the first row of the following array?
arr = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

print(f"First row is: {arr[0]}")

First row is: [1, 2, 3, 4]


In [22]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# Ans: To access the element at the third row and fourth column from the given NumPy array, we can use zero-based indexing. This means the first row is indexed as 0, the second row as 1, and the third row as 2. Similarly, the first column is indexed as 0, the second column as 1, the third column as 2, and the fourth column as 3.
# Example
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

element = arr[2, 3]

print(f"Element at third row and fourth column: {element}")

Element at third row and fourth column: 12


In [19]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

array_flatten = arr.flatten()
odd_indexed_element = array_flatten[::2]
print(f"Odd Indexes Are: {odd_indexed_element}")

Odd Indexes Are: [ 1  3  5  7  9 11]


In [23]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?
# Ans: We can generate a random 3x3 matrix with values between 0 and 1 using the numpy library, specifically the numpy.random.rand function. This function creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1).
# Example
arr = np.random.rand(3,3)
print(arr)

[[0.49573848 0.26192447 0.77597529]
 [0.31842173 0.20182524 0.91427571]
 [0.44023076 0.47745542 0.20210922]]


In [25]:
# 8. Describe the difference between np.random.rand and np.random.randn?
# Ans: The functions np.random.rand and np.random.randn from the NumPy library are both used to generate arrays of random numbers, but they generate numbers from different distributions.

#--------- np.random.rand----------:
# np.random.rand(d0, d1, ..., dn) generates an array of shape (d0, d1, ..., dn) with random floats in the half-open interval [0, 1).
# np.random.rand is Uniform distribution.

# example
uniform_matrix = np.random.rand(3, 3)
print("Uniform distribution (0 to 1):")
print(uniform_matrix)

# ----------np.random.randn--------:
# np.random.randn(d0, d1, ..., dn) generates an array of shape (d0, d1, ..., dn) with samples from the standard normal distribution.
# np.random.randn is Standard normal distribution (Gaussian).
# np.random.randn Range: Values can be any real number, but most will fall within a few standard deviations from the mean (approximately -3 to 3).

# example
normal_matrix = np.random.randn(3, 3)
print("Standard normal distribution (mean=0, std=1):")
print(normal_matrix)

Uniform distribution (0 to 1):
[[0.47285398 0.00139514 0.81413536]
 [0.19474576 0.41684164 0.82021134]
 [0.41204226 0.97954159 0.64596308]]
Standard normal distribution (mean=0, std=1):
[[-0.21412034  0.69752127 -1.6692382 ]
 [-0.84129609  1.15759545 -0.39546173]
 [ 1.38426288  0.53610472 -2.21610206]]


In [21]:
# 9. Write code to increase the dimension of the following array?
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

increase_dimension = np.expand_dims(arr, axis = 0)
print(increase_dimension)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [26]:
# 10. How to transpose the following array in NumPy?
# Ans: In NumPy, We can transpose an array using the numpy.transpose function or the .T attribute. Transposing an array swaps its rows and columns.

# Example
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

tenasposed_array = np.transpose(arr)
print(tenasposed_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [27]:
# 11. Consider the following matrix:
Matrix_A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

# Idex wise multiplication
array_multiply = Matrix_A2 * Matrix_B2
print(f"Index Wise Multiplication:\n {array_multiply}")

# Matix multiplication
Matrix_A2 = np.array([[1, 2, 3, 4], 
                      [5, 6, 7, 8], 
                      [9, 10, 11, 12]])

Matrix_B2 = np.array([[1, 2, 3], 
                      [4, 5, 6], 
                      [7, 8, 9], 
                      [10, 11, 12]])
matrix_multiply = Matrix_A2 @ Matrix_B2
print(f"Matix multiplication:\n {matrix_multiply}")

# Add both the matrix
Matrix_A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
addition_array = Matrix_A2 + Matrix_B2
print(f"Addition Array:\n {addition_array}")

# Subtact matrix B from A
substraction_array = Matrix_A2 - Matrix_B2
print(f"Substraction From B to A:\n {addition_array}")

# Devide Matrix B by A
division_array = Matrix_B2 / Matrix_A2
print(f"Division Array:\n{division_array}")

Index Wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matix multiplication:
 [[ 70  80  90]
 [158 184 210]
 [246 288 330]]
Addition Array:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Substraction From B to A:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Division Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
# 12. Which function in Numpy can be used to swap the byte order of an array?
# Ans: In NumPy, We can use the .byteswap() method to swap the byte order of an array. This method is useful when dealing with data that has a different endianness (byte order).

# Example
arr = np.array([1, 256, 65536], dtype=np.int32)
swapped_arr = arr.byteswap()
print(swapped_arr)

[16777216    65536      256]


In [29]:
# 13. What is the significance of the np.linalg.inv function?
# Ans: The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. In linear algebra, the inverse of a matrix.
# Example
A = np.array([[1, 2], [3, 4]])
# Compute the inverse
A_inv = np.linalg.inv(A)
print("Inverse matrix:\n", A_inv)

Inverse matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [30]:
# 14. What does the np.reshape function do, and how is it used?
# Ans: The np.reshape function in NumPy is used to change the shape of an array without changing its data. This function allows you to transform an array into a different shape, provided that the total number of elements remains constant.

# Example of Uses 
arr = np.arange(12)
reshapped_arr = arr.reshape(3,4)
print(reshapped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
# 15. What is broadcasting in Numpy?
# Ans: Broadcasting in NumPy is a set of rules and mechanisms that allow NumPy to perform element-wise operations on arrays of different shapes and sizes. It enables efficient computation by automatically expanding the smaller array to match the shape of the larger array without creating unnecessary copies of data.

# example
arr1 = np.array([[1,2,3], [11,22,33]])
arr2 = np.array([[23,24,25]])

Broadcasting_arr = arr1 + arr2
print(Broadcasting_arr)

[[24 26 28]
 [34 46 58]]
